---
- name: Set hostname to {{ hostname }}
  command: "hostnamectl --static set-hostname {{ hostname }}"

- name: Set timezone to {{ time_zone }}
  timezone:
    name: "{{ time_zone }}"

- name: Set locale to {{ locale }}
  command: "localectl set-locale {{ locale }}"

- name: Update CAs
  package:
    name : ca-certificates
    state : latest

