---
- name: Install PostgreSQL
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - postgresql
    - postgresql-contrib
    - python3-psycopg2
    - acl

# These are needed only for ansible to work:
#     - python3-psycopg2
#     - acl
